### ISSUE TITLE
QA annotation files

### ISSUE THREAD

**Issue by raghavgoyal14** [JonghwanMun/MarioQA#1]
Hi,

Is there a way you can provide me with the QA annotation files without having to compile the code?

Thanks,
Raghav

**Comment by raghavgoyal14** [comment]
I followed the instructions to generate QA, but came across this error:

```
$ bash run_generation_QA.sh
ln: failed to create symbolic link './event_logs': File exists
The parameters are as follows: 
logListPath     : generation_data/logFileLists.txt
confFile        : generation_data/configuration.json
qstTemplatePath : generation_data/templates.json
phrasePath      : generation_data/phrases.json
debugMode       : lev0

====> Start generating QAs for event_logs/play1.json
java.io.FileNotFoundException: generation_data/configuration.json (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at com.postechCVlab.MarioQA.EventLogs.loadConfigurationFile(EventLogs.java:192)
	at com.postechCVlab.MarioQA.EventLogs.<init>(EventLogs.java:80)
	at com.postechCVlab.MarioQA.QApairsGeneration.main(QApairsGeneration.java:62)
```

Can you point me to the steps to resolve the above?

Thanks in advance,
Raghav

**Comment by JonghwanMun** [comment]
To generate QA annotations, you need event log files, e.g., "event_logs/play1.json" (listed in generation_data/logFileList.txt).
To the end, you should play the game or download the files via "bash run_download_event_logs.sh"
